name: Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
    tags:
      - '*'

permissions:
  contents: write

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, '3.10', '3.11']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Variables
        id: set_variables
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global init.defaultBranch main

      - name: Install dependencies
        run: python -m pip install -U copier
      - name: Setup Tests(Unix)
        run: bash tests/setup.sh
        if: runner.os != 'Windows'

      - name: Run Tests
        run: |
          pdm use -f ${{ matrix.python-version }}
          pdm install -d
          pdm run test
        working-directory: ${{ github.workspace }}/tests/tmp

  Release:
    needs: Testing
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
